### ISSUE TITLE
Ajuste do background

### ISSUE THREAD

**Issue by LuizHenriqueVitorino** [ana-le-ticia/Curriculo-online---COMSOLID#1]
## Motivo
Todo background pode ser ser feito utilizando comandos nativos do CSS, inclusive os com degradê.

## Código a ser alterado:
```css
.principal{
    position: relative;
    height: 50%;

    display: flex;
    align-items: center;
    justify-content: space-evenly;
    
    background-size: cover;
    background-position: center;
    background-image: url('./img/fundo-azul.jpg');
}
```
